version: "3.8"
services:
  backend:
    image: "node:14.17.3"
    build:
      context: ./back
    working_dir: "/usr/src/app"
    ports:
      - "8080:3001"

  frontend:
    build:
      context: ./front
    working_dir: "/app"
    ports:
      - "8081:3000"
    command: "yarn start"
