version: "4.9.0"
services:
  backend:
    image: "node:14.17.3"
    volumes:
      - "./:/home/node/app"
    working_dir: "/home/node/app"
    ports:
      - "8080:3001"
    command: "node server.js"
  frontend:
    image: "node:14.17.3"
    volumes:
      - "./:/schoolmaterial"
    working_dir: "/schoolmaterial"
    ports:
      - "8081:3000"
    command: "yarn start"
